// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediaproxy/v1/mediaproxy.proto

module protocol.mediaproxy.v1.mediaproxy;

import google.protobuf;
import protocol.harmonytypes.v1.types;

enum protocVersion = 3012004;

class SiteMetadata
{
    @Proto(1) string siteTitle = protoDefaultValue!string;
    @Proto(2) string pageTitle = protoDefaultValue!string;
    @Proto(3) string kind = protoDefaultValue!string;
    @Proto(4) string description = protoDefaultValue!string;
    @Proto(5) string url = protoDefaultValue!string;
    @Proto(6) string image = protoDefaultValue!string;
}

class FetchLinkMetadataRequest
{
    @Proto(1) string url = protoDefaultValue!string;
}

class InstantViewRequest
{
    @Proto(1) string url = protoDefaultValue!string;
}

class InstantViewResponse
{
    @Proto(1) SiteMetadata metadata = protoDefaultValue!SiteMetadata;
    @Proto(2) string content = protoDefaultValue!string;
    @Proto(3) bool isValid = protoDefaultValue!bool;
}

class CanInstantViewResponse
{
    @Proto(1) bool canInstantView = protoDefaultValue!bool;
}
import harmonytemplates.templates;
