// Generated by the gRPC-dlang plugin.

module protocol.chat.v1.channelsRpc;

import protocol.chat.v1.channels;
import protocol.harmonytypes.v1.types;

import grpc;
import google.protobuf;
import hunt.logging;

import core.thread;
import std.array;
import std.traits;


