// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat/v1/chat.proto

module protocol.chat.v1.chat;

import google.protobuf;
import google.protobuf.empty;
import protocol.harmonytypes.v1.types;
import protocol.chat.v1.profile;
import protocol.chat.v1.guilds;
import protocol.chat.v1.channels;
import protocol.chat.v1.messages;
import protocol.chat.v1.emotes;
import protocol.chat.v1.permissions;
import protocol.chat.v1.streaming;
import protocol.chat.v1.postbox;

enum protocVersion = 3012004;
