// Generated by the gRPC-dlang plugin.

module protocol.chat.v1.emotesRpc;

import protocol.chat.v1.emotes;

import grpc;
import google.protobuf;
import hunt.logging;

import core.thread;
import std.array;
import std.traits;


