// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat/v1/guilds.proto

module protocol.chat.v1.guilds;

import google.protobuf;
import protocol.harmonytypes.v1.types;

enum protocVersion = 3012004;

class CreateGuildRequest
{
    @Proto(1) string guildName = protoDefaultValue!string;
    @Proto(2) string pictureUrl = protoDefaultValue!string;
    @Proto(3) Metadata metadata = protoDefaultValue!Metadata;
}

class CreateGuildResponse
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class CreateInviteRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) string name = protoDefaultValue!string;
    @Proto(3) int possibleUses = protoDefaultValue!int;
}

class CreateInviteResponse
{
    @Proto(1) string name = protoDefaultValue!string;
}

class GetGuildListRequest
{
}

class GetGuildListResponse
{
    @Proto(1) GuildListEntry[] guilds = protoDefaultValue!(GuildListEntry[]);

    static class GuildListEntry
    {
        @Proto(1) ulong guildId = protoDefaultValue!ulong;
        @Proto(2) string host = protoDefaultValue!string;
    }
}

class GetGuildRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class GetGuildResponse
{
    @Proto(1) string guildName = protoDefaultValue!string;
    @Proto(2) ulong guildOwner = protoDefaultValue!ulong;
    @Proto(3) string guildPicture = protoDefaultValue!string;
    @Proto(4) Metadata metadata = protoDefaultValue!Metadata;
}

class GetGuildInvitesRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class GetGuildInvitesResponse
{
    @Proto(1) Invite[] invites = protoDefaultValue!(Invite[]);

    static class Invite
    {
        @Proto(1) string inviteId = protoDefaultValue!string;
        @Proto(2) int possibleUses = protoDefaultValue!int;
        @Proto(3) int useCount = protoDefaultValue!int;
    }
}

class GetGuildMembersRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class GetGuildMembersResponse
{
    @Proto(1) ulong[] members = protoDefaultValue!(ulong[]);
}

class UpdateGuildInformationRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) string newGuildName = protoDefaultValue!string;
    @Proto(3) bool updateGuildName = protoDefaultValue!bool;
    @Proto(4) string newGuildPicture = protoDefaultValue!string;
    @Proto(5) bool updateGuildPicture = protoDefaultValue!bool;
    @Proto(6) Metadata metadata = protoDefaultValue!Metadata;
    @Proto(7) bool updateMetadata = protoDefaultValue!bool;
}

class DeleteGuildRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class DeleteInviteRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) string inviteId = protoDefaultValue!string;
}

class JoinGuildRequest
{
    @Proto(1) string inviteId = protoDefaultValue!string;
}

class JoinGuildResponse
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class PreviewGuildRequest
{
    @Proto(1) string inviteId = protoDefaultValue!string;
}

class PreviewGuildResponse
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string avatar = protoDefaultValue!string;
    @Proto(3) ulong memberCount = protoDefaultValue!ulong;
}

class LeaveGuildRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
}

class AddGuildToGuildListRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) string homeserver = protoDefaultValue!string;
}

class AddGuildToGuildListResponse
{
}

class RemoveGuildFromGuildListRequest
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) string homeserver = protoDefaultValue!string;
}

class RemoveGuildFromGuildListResponse
{
}
