// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat/v1/postbox.proto

module protocol.chat.v1.postbox;

import google.protobuf;

enum protocVersion = 3012004;

class SyncRequest
{
    @Proto(1) string token = protoDefaultValue!string;
    @Proto(2) string host = protoDefaultValue!string;
}

class SyncEvent
{
    enum EventCase
    {
        eventNotSet = 0,
        dmInvite = 1,
    }
    EventCase _eventCase = EventCase.eventNotSet;
    @property EventCase eventCase() { return _eventCase; }
    void clearEvent() { _eventCase = EventCase.eventNotSet; }
    @Oneof("_eventCase") union
    {
        @Proto(1) DMInvite _dmInvite = protoDefaultValue!DMInvite; mixin(oneofAccessors!_dmInvite);
    }

    static class DMInvite
    {
        @Proto(1) string userName = protoDefaultValue!string;
        @Proto(2) string userAvatar = protoDefaultValue!string;
        @Proto(3) string dmName = protoDefaultValue!string;
        @Proto(4) string dmAvatar = protoDefaultValue!string;
        @Proto(5) string inviteId = protoDefaultValue!string;
    }
}
import harmonytemplates.templates;
