// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat/v1/profile.proto

module protocol.chat.v1.profile;

import google.protobuf;
import protocol.harmonytypes.v1.types;

enum protocVersion = 3012004;

class GetUserRequest
{
    @Proto(1) ulong userId = protoDefaultValue!ulong;
}

class GetUserResponse
{
    @Proto(1) string userName = protoDefaultValue!string;
    @Proto(2) string userAvatar = protoDefaultValue!string;
    @Proto(3) UserStatus userStatus = protoDefaultValue!UserStatus;
    @Proto(4) bool isBot = protoDefaultValue!bool;
}

class GetUserMetadataRequest
{
    @Proto(1) string appId = protoDefaultValue!string;
}

class GetUserMetadataResponse
{
    @Proto(1) string metadata = protoDefaultValue!string;
}

class ProfileUpdateRequest
{
    @Proto(1) string newUsername = protoDefaultValue!string;
    @Proto(2) bool updateUsername = protoDefaultValue!bool;
    @Proto(3) string newAvatar = protoDefaultValue!string;
    @Proto(4) bool updateAvatar = protoDefaultValue!bool;
    @Proto(5) UserStatus newStatus = protoDefaultValue!UserStatus;
    @Proto(6) bool updateStatus = protoDefaultValue!bool;
    @Proto(7) bool isBot = protoDefaultValue!bool;
    @Proto(8) bool updateIsBot = protoDefaultValue!bool;
}
