// Generated by the gRPC-dlang plugin.

module protocol.chat.v1.streamingRpc;

import protocol.chat.v1.streaming;
import protocol.harmonytypes.v1.types;
import google.protobuf.timestamp;

import grpc;
import google.protobuf;
import hunt.logging;

import core.thread;
import std.array;
import std.traits;


