// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/v1/auth.proto

module protocol.auth.v1.auth;

import google.protobuf;
import google.protobuf.empty;

enum protocVersion = 3012004;

class BeginAuthResponse
{
    @Proto(1) string authId = protoDefaultValue!string;
}

class Session
{
    @Proto(1) ulong userId = protoDefaultValue!ulong;
    @Proto(2) string sessionToken = protoDefaultValue!string;
}

class AuthStep
{
    @Proto(1) string fallbackUrl = protoDefaultValue!string;
    @Proto(2) bool canGoBack = protoDefaultValue!bool;
    enum StepCase
    {
        stepNotSet = 0,
        choice = 3,
        form = 4,
        session = 5,
        waiting = 6,
    }
    StepCase _stepCase = StepCase.stepNotSet;
    @property StepCase stepCase() { return _stepCase; }
    void clearStep() { _stepCase = StepCase.stepNotSet; }
    @Oneof("_stepCase") union
    {
        @Proto(3) Choice _choice = protoDefaultValue!Choice; mixin(oneofAccessors!_choice);
        @Proto(4) Form _form; mixin(oneofAccessors!_form);
        @Proto(5) Session _session; mixin(oneofAccessors!_session);
        @Proto(6) Waiting _waiting; mixin(oneofAccessors!_waiting);
    }

    static class Choice
    {
        @Proto(1) string title = protoDefaultValue!string;
        @Proto(2) string[] options = protoDefaultValue!(string[]);
    }

    static class Form
    {
        @Proto(1) string title = protoDefaultValue!string;
        @Proto(2) FormField[] fields = protoDefaultValue!(FormField[]);

        static class FormField
        {
            @Proto(1) string name = protoDefaultValue!string;
            @Proto(2) string type = protoDefaultValue!string;
        }
    }

    static class Waiting
    {
        @Proto(1) string title = protoDefaultValue!string;
        @Proto(2) string description = protoDefaultValue!string;
    }
}

class NextStepRequest
{
    @Proto(1) string authId = protoDefaultValue!string;
    enum StepCase
    {
        stepNotSet = 0,
        choice = 2,
        form = 3,
    }
    StepCase _stepCase = StepCase.stepNotSet;
    @property StepCase stepCase() { return _stepCase; }
    void clearStep() { _stepCase = StepCase.stepNotSet; }
    @Oneof("_stepCase") union
    {
        @Proto(2) Choice _choice = protoDefaultValue!Choice; mixin(oneofAccessors!_choice);
        @Proto(3) Form _form; mixin(oneofAccessors!_form);
    }

    static class Choice
    {
        @Proto(1) string choice = protoDefaultValue!string;
    }

    static class FormFields
    {
        enum FieldCase
        {
            fieldNotSet = 0,
            bytes = 1,
            string_ = 2,
            number = 3,
        }
        FieldCase _fieldCase = FieldCase.fieldNotSet;
        @property FieldCase fieldCase() { return _fieldCase; }
        void clearField() { _fieldCase = FieldCase.fieldNotSet; }
        @Oneof("_fieldCase") union
        {
            @Proto(1) bytes _bytes = []; mixin(oneofAccessors!_bytes);
            @Proto(2) string _string_; mixin(oneofAccessors!_string_);
            @Proto(3) long _number; mixin(oneofAccessors!_number);
        }
    }

    static class Form
    {
        @Proto(1) FormFields[] fields = protoDefaultValue!(FormFields[]);
    }
}

class StepBackRequest
{
    @Proto(1) string authId = protoDefaultValue!string;
}

class StreamStepsRequest
{
    @Proto(1) string authId = protoDefaultValue!string;
}

class FederateRequest
{
    @Proto(1) string target = protoDefaultValue!string;
}

class FederateReply
{
    @Proto(1) string token = protoDefaultValue!string;
    @Proto(2) string nonce = protoDefaultValue!string;
}

class KeyReply
{
    @Proto(1) string key = protoDefaultValue!string;
}

class LoginFederatedRequest
{
    @Proto(1) string authToken = protoDefaultValue!string;
    @Proto(2) string domain = protoDefaultValue!string;
}
