// Generated by the gRPC-dlang plugin.

module protocol.harmonytypes.v1.typesRpc;

import protocol.harmonytypes.v1.types;
import google.protobuf.timestamp;
import google.protobuf.empty;
import google.protobuf.any;


import grpc;
import google.protobuf;
import hunt.logging;

import core.thread;
import std.array;
import std.traits;


