// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: harmonytypes/v1/types.proto

module protocol.harmonytypes.v1.types;

import google.protobuf;
import google.protobuf.timestamp;
import google.protobuf.empty;
import google.protobuf.any;


enum protocVersion = 3012004;

class HarmonyMethodMetadata
{
    @Proto(1) bool requiresAuthentication = protoDefaultValue!bool;
    @Proto(2) bool requiresLocal = protoDefaultValue!bool;
    @Proto(3) string requiresPermissionNode = protoDefaultValue!string;
}

class Override
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) string avatar = protoDefaultValue!string;
    enum ReasonCase
    {
        reasonNotSet = 0,
        userDefined = 3,
        webhook = 4,
        systemPlurality = 5,
        systemMessage = 6,
        bridge = 7,
    }
    ReasonCase _reasonCase = ReasonCase.reasonNotSet;
    @property ReasonCase reasonCase() { return _reasonCase; }
    void clearReason() { _reasonCase = ReasonCase.reasonNotSet; }
    @Oneof("_reasonCase") union
    {
        @Proto(3) string _userDefined = protoDefaultValue!string; mixin(oneofAccessors!_userDefined);
        @Proto(4) Empty _webhook; mixin(oneofAccessors!_webhook);
        @Proto(5) Empty _systemPlurality; mixin(oneofAccessors!_systemPlurality);
        @Proto(6) Empty _systemMessage; mixin(oneofAccessors!_systemMessage);
        @Proto(7) Empty _bridge; mixin(oneofAccessors!_bridge);
    }
}

class Action
{
    @Proto(1) string text = protoDefaultValue!string;
    @Proto(2) string url = protoDefaultValue!string;
    @Proto(3) string id = protoDefaultValue!string;
    @Proto(4) ActionType type = protoDefaultValue!ActionType;
    @Proto(5) ActionPresentation presentation = protoDefaultValue!ActionPresentation;
    @Proto(6) Action[] children = protoDefaultValue!(Action[]);
}

class EmbedHeading
{
    @Proto(1) string text = protoDefaultValue!string;
    @Proto(2) string subtext = protoDefaultValue!string;
    @Proto(3) string url = protoDefaultValue!string;
    @Proto(4) string icon = protoDefaultValue!string;
}

class EmbedField
{
    @Proto(1) string title = protoDefaultValue!string;
    @Proto(2) string subtitle = protoDefaultValue!string;
    @Proto(3) string body_ = protoDefaultValue!string;
    @Proto(4) string imageUrl = protoDefaultValue!string;
    @Proto(5) FieldPresentation presentation = protoDefaultValue!FieldPresentation;
    @Proto(6) Action[] actions = protoDefaultValue!(Action[]);
}

class Embed
{
    @Proto(1) string title = protoDefaultValue!string;
    @Proto(2) string body_ = protoDefaultValue!string;
    @Proto(3) long color = protoDefaultValue!long;
    @Proto(4) EmbedHeading header = protoDefaultValue!EmbedHeading;
    @Proto(5) EmbedHeading footer = protoDefaultValue!EmbedHeading;
    @Proto(6) EmbedField[] fields = protoDefaultValue!(EmbedField[]);
    @Proto(7) Action[] actions = protoDefaultValue!(Action[]);
}

class Attachment
{
    @Proto(1) string id = protoDefaultValue!string;
    @Proto(2) string name = protoDefaultValue!string;
    @Proto(3) string type = protoDefaultValue!string;
    @Proto(4) int size = protoDefaultValue!int;
}

class Metadata
{
    @Proto(1) string kind = protoDefaultValue!string;
    @Proto(2) Any[string] extension = protoDefaultValue!(Any[string]);
}

class Message
{
    @Proto(1) ulong guildId = protoDefaultValue!ulong;
    @Proto(2) ulong channelId = protoDefaultValue!ulong;
    @Proto(3) ulong messageId = protoDefaultValue!ulong;
    @Proto(4) ulong authorId = protoDefaultValue!ulong;
    @Proto(5) Timestamp createdAt = protoDefaultValue!Timestamp;
    @Proto(6) Timestamp editedAt = protoDefaultValue!Timestamp;
    @Proto(7) string content = protoDefaultValue!string;
    @Proto(8) Embed[] embeds = protoDefaultValue!(Embed[]);
    @Proto(9) Action[] actions = protoDefaultValue!(Action[]);
    @Proto(10) Attachment[] attachments = protoDefaultValue!(Attachment[]);
    @Proto(11) ulong inReplyTo = protoDefaultValue!ulong;
    @Proto(12) Override overrides = protoDefaultValue!Override;
    @Proto(13) Metadata metadata = protoDefaultValue!Metadata;
}

enum UserStatus
{
    USER_STATUS_ONLINE_UNSPECIFIED = 0,
    USER_STATUS_STREAMING = 1,
    USER_STATUS_DO_NOT_DISTURB = 2,
    USER_STATUS_IDLE = 3,
    USER_STATUS_OFFLINE = 4,
}

enum ActionType
{
    Normal = 0,
    Primary = 1,
    Destructive = 2,
}

enum ActionPresentation
{
    Button = 0,
    Dropdown = 1,
    Menu = 2,
    SmallEntry = 3,
    LargeEntry = 4,
}

enum FieldPresentation
{
    Data = 0,
    CaptionedImage = 1,
    Row = 2,
}
